### ISSUE TITLE
Exception on Image preview dashlet

### ISSUE THREAD

**Issue by corsarof** [Alfresco/chef-alfresco#10]
Image Preview
04260013 Wrapped Exception (with status template): 04260088 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/images.get.js': 04260087 Failed to execute search: +PATH:"/app:company_home/st:sites/cm:swsdp/cm:documentLibrary//*" +TYPE:"cm:content" +@cm\:content.mimetype:image/*

**Comment by maoo** [comment]
fixed on master
