### ISSUE TITLE
User invite email has wrong URL

### ISSUE THREAD

**Issue by corsarof** [Alfresco/chef-alfresco#11]
When inviting a new user to a site the email is correctly sent however the URL is wrong: http://localhost.localdomain:8080/share/page/accept-invite?inviteId=activiti$34&inviteeUserName=fab_cor&siteShortName=test&inviteTicket=1d0adc42-21ea-43a9-aa86-54896550741a

That should be instead --> http://localhost:8080/share/page/accept-invite?inviteId=activiti$34&inviteeUserName=fab_cor&siteShortName=test&inviteTicket=1d0adc42-21ea-43a9-aa86-54896550741a

**Comment by enzor** [comment]
not relevant anymore - closing
