### ISSUE TITLE
Adding SSL

### ISSUE THREAD

**Issue by mtwallach** [Alfresco/chef-alfresco#120]
[proxy.tar.gz](https://github.com/Alfresco/chef-alfresco/files/487237/proxy.tar.gz)
[proxy.tar.gz.txt](https://github.com/Alfresco/chef-alfresco/files/487240/proxy.tar.gz.txt)
[nginx.conf.txt](https://github.com/Alfresco/chef-alfresco/files/487241/nginx.conf.txt)

We are using a wrapper cookbook to generate a separate Nginx proxy instance in AWS for our Alfresco stack.

Our wrapper includes the Alfresco Chef cookbook which I believe includes the “nginx 2.7.6” cookbook from the Chef Supermarket.

I was able to get a good http configuration set up using the template parameters, but have been unsuccessful in getting a configuration with SSL options enabled.  We have tried adding the SSL parameter section to both attributes/default.rb and to a separate included recipe in recipes/_nginx-conf.rb.  Neither seems to work.

Would you have any words of wisdom on how to get this enabled or be able to assist us in doing so?  I have attached the current wrapper cookbook and generated nginx.conf file.

**Comment by nicdoye** [comment]
Hi @mtwallach, 

I can't see the attachment. 

Nic

**Comment by mtwallach** [comment]
Added attachents. .txt extension added to allow for upload to issue

**Comment by enzor** [comment]
Hi Mike,

sorry for the very delayed response, but lately i was busy in getting a proper roadmap for this project.
Full support for SSL is in our 0.9 milestone, which will come early next year, we will try to stick to our schedule as best as we can :)
