### ISSUE TITLE
Edit online needs ssl 

### ISSUE THREAD

**Issue by corsarof** [Alfresco/chef-alfresco#13]
Currently Edit online opens Office however it cannot load the document because there is no SSL connection set.

This redirects the user here --> https://support.microsoft.com/en-gb/kb/2498069

**Comment by steverigby** [comment]
It would be ideal that on local environments or those not linked to a databag containing authority provided ssl certs that one is created.
This cookbook could be used to create a local ssl cert for testing purposes in the environment:
https://github.com/onddo/ssl_certificate-cookbook

This would allow for production matching configuration re ports and http/https to be used locally.

**Comment by maoo** [comment]
SSL is offloaded to haproxy. closing this.
