### ISSUE TITLE
Many errors and fix, then error

### ISSUE THREAD

**Issue by yaqxeqtt** [Alfresco/chef-alfresco#16]
Hi,
I tried to run git clone and kitchen converge, then many errors occurred (and my temporary fixs):

1. Guest Additions Error
 * $ sudo ln -s /usr/include/ /lib/modules/3.10.0-123.el7.x86_64/build/
2. Error executing action `put` on resource 'maven[*]'
 * **recipes/_tomcat-attributes.rb**
  * node.default['artifacts']['catalina-jmx']['url'] = "http://central.maven.org/maven2/org/apache/tomcat/#{node.default['artifacts']['catalina-jmx']['artifactId']}/#{node.default['artifacts']['catalina-jmx']['version']}/#{node.default['artifacts']['catalina-jmx']['artifactId']}-#{node.default['artifacts']['catalina-jmx']['version']}.#{node.default['artifacts']['catalina-jmx']['type']}"
 * **recipes/_repo-attributes.rb**
  * node.default['artifacts']['mysql']['url'] = "http://central.maven.org/maven2/#{node.default['artifacts']['mysql']['groupId']}/#{node.default['artifacts']['mysql']['artifactId']}/#{node.default['artifacts']['mysql']['version']}/#{node.default['artifacts']['mysql']['artifactId']}-#{node.default['artifacts']['mysql']['version']}.#{node.default['artifacts']['mysql']['type']}"
  * node.default['artifacts']['keystore']['url'] = "https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/#{node.default['artifacts']['keystore']['artifactId']}/#{node.default['artifacts']['keystore']['version']}/#{node.default['artifacts']['keystore']['artifactId']}-#{node.default['artifacts']['keystore']['version']}.#{node.default['artifacts']['keystore']['type']}"
  * node.default['artifacts']['alfresco']['url'] = "https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/#{node.default['artifacts']['alfresco']['artifactId']}/#{node.default['artifacts']['alfresco']['version']}/#{node.default['artifacts']['alfresco']['artifactId']}-#{node.default['artifacts']['alfresco']['version']}.#{node.default['artifacts']['alfresco']['type']}"
  * node.default['artifacts']['alfresco-mmt']['url'] = "https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/#{node.default['artifacts']['alfresco-mmt']['artifactId']}/#{node.default['artifacts']['alfresco-mmt']['version']}/#{node.default['artifacts']['alfresco-mmt']['artifactId']}-#{node.default['artifacts']['alfresco-mmt']['version']}.#{node.default['artifacts']['alfresco-mmt']['type']}"
 * **recipes/_share-attributes.rb**
  * node.default['artifacts']['share']['url'] = "https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/#{node.default['artifacts']['share']['artifactId']}/#{node.default['artifacts']['share']['version']}/#{node.default['artifacts']['share']['artifactId']}-#{node.default['artifacts']['share']['version']}.#{node.default['artifacts']['share']['type']}"
 * **recipes/_solr-attributes.rb**
  * node.default['artifacts']['solrhome']['url'] = "https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/#{node.default['artifacts']['solrhome']['artifactId']}/#{node.default['artifacts']['solrhome']['version']}/#{node.default['artifacts']['solrhome']['artifactId']}-#{node.default['artifacts']['solrhome']['version']}-#{node.default['artifacts']['solrhome']['classifier']}.#{node.default['artifacts']['solrhome']['type']}"
  * node.default['artifacts']['solr4']['url'] = "https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/#{node.default['artifacts']['solr4']['artifactId']}/#{node.default['artifacts']['solr4']['version']}/#{node.default['artifacts']['solr4']['artifactId']}-#{node.default['artifacts']['solr4']['version']}.#{node.default['artifacts']['solr4']['type']}"
 * **recipes/_rm-attributes.rb**
  * node.default['artifacts']['rm']['url'] = "https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/#{node.default['artifacts']['rm']['artifactId']}/#{node.default['artifacts']['rm']['version']}/#{node.default['artifacts']['rm']['artifactId']}-#{node.default['artifacts']['rm']['version']}.#{node.default['artifacts']['rm']['type']}"
  * node.default['artifacts']['rm-share']['url'] = "https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/#{node.default['artifacts']['rm-share']['artifactId']}/#{node.default['artifacts']['rm-share']['version']}/#{node.default['artifacts']['rm-share']['artifactId']}-#{node.default['artifacts']['rm-share']['version']}.#{node.default['artifacts']['rm-share']['type']}"
 * **recipes/_googledocs-attributes.rb**
  * node.default['artifacts']['googledocs-repo']['url'] = "https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/integrations/#{node.default['artifacts']['googledocs-repo']['artifactId']}/#{node.default['artifacts']['googledocs-repo']['version']}/#{node.default['artifacts']['googledocs-repo']['artifactId']}-#{node.default['artifacts']['googledocs-repo']['version']}.#{node.default['artifacts']['googledocs-repo']['type']}"
  * node.default['artifacts']['googledocs-share']['url'] = "https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/integrations/#{node.default['artifacts']['googledocs-share']['artifactId']}/#{node.default['artifacts']['googledocs-share']['version']}/#{node.default['artifacts']['googledocs-share']['artifactId']}-#{node.default['artifacts']['googledocs-share']['version']}.#{node.default['artifacts']['googledocs-share']['type']}"
3. Error executing action `create` on resource 'remote_file[/tmp/kitchen/cache/keystore.jar]'
 * .kitchen.yml(71):"version" : "5.0.d"
4. Error executing action `run` on resource 'execute[run-nossl-patch.sh]'
 * the line feed code from CR+LF to LF

...kithen converge is finished. 

But http://localhost:8800/share is alfresco error page. I found following error log.

* /usr/share/tomcat-share/logs/share.log
 * ERROR [org.alfresco.web.site] org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException

Do you have any suggestion to fix it? 

My environments:
* Windows 7 sp1 x64
* Chef Development Kit Version: 0.6.2
* chef-client version: 12.3.0
* berks version: 3.2.4
* kitchen version: 1.4.0
* Vagrant 1.7.4
* VirtualBox 5.0.2

**Comment by maoo** [comment]
Hi @yaqxeqtt, thanks a lot for your feedback; I'll answer to each of your items:

1. Never used Guest Additions, but thanks for the tip, I added it into the docs
2. This shouldn't be necessary, I think that your download problems were coming from 3.
3. Sorry, my mistake, default version should be community one; I already pushed the fix
4. I'm not sure I understand this; maybe you can send me a pull request?

Regarding the share issue, I'm trying to reproduce it right now; can you also check /var/log/tomcat-alfresco/alfresco.log and catalina.out.<date> on /var/log/tomcat-[alfresco|solr|share] ?

Thanks.

**Comment by maoo** [comment]
I could reproduce and fix the issue; now you should be able - after pulling the changes - to run `kitchen converge chef-alfresco-centos-70` and access to http://localhost:8800/share with admin/admin.

Please let me know if I can help any further and thanks a lot for spotting the issue!

**Comment by yaqxeqtt** [comment]
Hi @maoo, thank you for your reply.

I retried to run `git clone` and `kitchen converge chef-alfresco-centos-70`.

When I access to http://localhost:8080/share/, Alfresco login page is displayed instead of Server error page. But I can not login with admin/admin because of authentication and/or etc.
And http://localhost:8090/solr/ is blank page.
http://localhost:8070/alfresco/ is good, maybe.

I found following error in /var/log/tomcat-solr/solr.log.
```
ERROR [org.alfresco.solr.tracker.AbstractTracker] Model tracking failed
org.alfresco.error.AlfrescoRuntimeException: 08080000 GetModelsDiff return status is 503
        at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1091)
        at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:249)
        at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:207)
        at org.alfresco.solr.tracker.ModelTracker.ensureFirstModelSync(ModelTracker.java:229)
        at org.alfresco.solr.tracker.CoreWatcherJob.registerForCore(CoreWatcherJob.java:131)
        at org.alfresco.solr.tracker.CoreWatcherJob.execute(CoreWatcherJob.java:74)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
```

There is no error in the others(/var/log/tomcat-[alfresco|solr|share]/*.log).

It is my mistake about 4 of my items. Git option, Auto CrLf convert, is enabled on my testing machine.
I would like to thank you for your time and patience.

**Comment by maoo** [comment]
Hi @yaqxeqtt! 
Few notes that may be helpful:

1. We use the new `index.subsystem.name=solr4` therefore the Solr URL is `http://localhost:8090/solr4`; can you try that one? I found an issue on Solr too, fixed by commit https://github.com/Alfresco/chef-alfresco/commit/663cfb408b1297d10d98d985a0297229d80aa839 ; could you check (using kitchen login) if the files `/usr/share/tomcat/alf_data/solrhome/workspace-SpacesStore/conf/solrcore.properties` and `/usr/share/tomcat/alf_data/solrhome/archive-SpacesStore/conf/solrcore.properties` include the proper property value for `alfresco.baseUrl=/alfresco` (and not `alfresco.baseUrl=alfresco` as it used to be)?
2. Alfresco Share should work properly also without Solr; the fix I pushed yesterday was to make sure that `/usr/share/tomcat/shared/classes/alfresco/web-extension/share-config-custom.xml` includes the right alfresco endpoints (URLs starting with `http://localhost:9000/alfresco` (and not `http://localhost:9000alfresco` as it used to be)

Could you please check the mentioned files and let me know? I'd have expected that a `kitchen converge chef-alfresco-centos-70`fixed it.
If files are ok, but errors still appear, could you try to restart services with
```
service tomcat-share restart
service tomcat-solr restart
```
Again, I was expecting Chef to take care of this.

Thanks!

**Comment by yaqxeqtt** [comment]
Hi @maoo!
Thank you!! Everything is OK!!

1. http://localhost:8090/solr4/ is ok! Please fix README.md. Files are ok.
2. the endpoint-url is `http://localhost:9000/alfresco/s`.

I try to restart service, `service tomcat-share restart`. I can login with admin/admin!

Thanks a lot!!
