### ISSUE TITLE
Default password hashing cryptography

### ISSUE THREAD

**Issue by SubatomicHero** [Alfresco/chef-alfresco#160]
The default password hashing cryptography needs updating from md4 to bcrypt following this guide and setting the correct property:

http://docs.alfresco.com/5.1/concepts/bcrypt-overview.html

We should make sure we are installing Alfresco 5.1.1 to support the new property type.

**Comment by enzor** [comment]
if it's something that is supported only in 5.1.1 then this belong to a wrapper cookbook, not to the core.
This cookbook aim is to give you the tool to override it's own properties  and to use every version of alfresco with it's custom properties. is a good point for documentation tho - need to point to the alfresco docs as much as possible to clarify

**Comment by enzor** [comment]
Closing as this should not be an issue of the core, rather a documentation issue
