### ISSUE TITLE
haproxy configuration for solr6 port doesn't work

### ISSUE THREAD

**Issue by enzor** [Alfresco/chef-alfresco#194]
https://github.com/Alfresco/chef-alfresco/blob/master/attributes/haproxy.rb#L208

If solr6 exists, configuration doesn't use the solr6 port ( uses the solr4 one, but in this case the attribute will be blank ) 
This is present only on when doing clustering ( aws marketplace )

**Comment by toniblyx** [comment]
same issue happens for haproxy-discovery, when the cron job runs it doesn't add the port.

**Comment by toniblyx** [comment]
I added lines below to /etc/chef/haproxy-discovery.json

"haproxy" : {
      "logformat" : "#- wibble",
      "ec2": {
        "discovery_enabled" : true
      },
      "backends" : {
          "roles" : {
            "solr" : {
              "port" : 8090
            }
          }
        }
     },

and discovery set it properly

**Comment by marcomancuso** [comment]
what do you mean it uses the solr4 port? Solr6 and Solr4 are configured to use the same port, 8090

**Comment by marcomancuso** [comment]
Fixed
