### ISSUE TITLE
haproxy-config cron job reset default values instead of using it's wrapping cookbook ones

### ISSUE THREAD

**Issue by enzor** [Alfresco/chef-alfresco#201]
Problem Definition
==============

In our clustered systems we use different way for discovery of other instances.
To do this we run the `haproxy-config` recipe to regenerate the internal addresses, as we use haproxy for internal service discovery.
Problem is, when used from a wrapper cookbook, will use the default `chef-alfresco` attributes, and not the ones in the wrapper cookbook itself - de facto resetting all specific configuration we do for other projects.

This may not be entirely solved inside chef-alfresco, but the methodology on how to solve it should be documented and noted in our wiki. 
Also,this need to be included in [chef-alfresco-internal-lb](https://github.com/Alfresco/chef-alfresco-internal-lb) cookbook, as we are moving all the internal-lb related stuff there.

**Comment by enzor** [comment]
Addressed and solved in #204 . Currently in testing

**Comment by enzor** [comment]
@amohammedalfresco has this been solved?

**Comment by amohammedalfresco** [comment]
Hi @enzor, this now solved.  A wrapper cookbook can now use/override a custom ha-proxy cron json file to permanently persist haproxy attributes defined inside the wrapper cookbook.

For example define below inside `mywrapper-cookbook`:
Attribute:
```
default['haproxy']['ec2']['discovery_chef_json']['source'] = 'haproxy/haproxy-discovery.json.erb'
```
Template:
```
{
    "name": "haproxy-discovery",
    "tomcat" : {
      "jvm_route" : "<%= node['tomcat']['jvm_route'] %>"
    },
    "alfresco": {
      "components": <%= node['alfresco']['components'] %>
    },
    "haproxy" : {
      "logformat" : <%= node['haproxy']['logformat'].to_json %>,
      "ec2": {
        "discovery_enabled" : true
      }
     },
    "commons" : {
        "ec2_discovery" : <%= node['commons']['ec2_discovery'].to_json %>
    },
    "run_list": ["mywrapper-cookbook::haproxy-config"]  
}
```

Recipe:
```
include_recipe 'alfresco::haproxy'
begin
  r = resources(template: node['haproxy']['ec2']['discovery_chef_json']['dest'])
  r.cookbook 'mywrapper-cookbook'
  r.source node['haproxy']['ec2']['discovery_chef_json']['source']
  r.notifies :reload, 'service[haproxy]', :immediately
rescue Chef::Exceptions::ResourceNotFound
  Chef::Log.warn 'could not find template in my wrapper cookbook to override with chef-alfresco cookbook!'
end
```
Recipe `haproxy-config.rb`:
```
include_recipe 'alfresco::haproxy-config'
```

This should fix ha-proxy attribute persistence in a wrapper cookbook.

**Comment by enzor** [comment]
cool, closing the issue and putting it in the documentation.
great job @amohammedalfresco !! 👍
