### ISSUE TITLE
haproxy_config.rb - hard coded error codes

### ISSUE THREAD

**Issue by mtwallach** [Alfresco/chef-alfresco#210]
in haproxy_config.rb there are error code values that result in:
node.default['haproxy']['frontends']['external']['entries'] << "rspideny . if is_#{error_code}_error"

Having an issue where when webscripts fail with one of these error codes results is error page not handled and user must wait for timeout.

**Comment by marcomancuso** [comment]
@mtwallach, do you mean when the webscript fails with an error code NOT INCLUDED in 400 403 408 500 502 503 504 or the other way round?

**Comment by mtwallach** [comment]
other way around. webscript does fail with 400,403,408 500 502 503 504.

**Comment by marcomancuso** [comment]
I've been able to reproduce the issue:

1. converge any chef-alfresco suite
2. Create a file called test-210.get.desc.xml and upload it into 
Repository> Data Dictionary> Web Scripts> org> alfresco> test
```
<webscript>
    <shortname>Test issue 210</shortname>
    <description>Test issue 210</description>
    <url>/test/issue?errorcode={errorcode}</url>
    <authentication>user</authentication>
    <format default="html"></format>
    <family>Devops Test</family>
</webscript>
```
2. Create a file called test-210.get.js and upload it into 
Repository> Data Dictionary> Web Scripts> org> alfresco> test

```
var errorcode = parseInt(args["errorcode"])
status.code = errorcode;
status.message = "Error!";
status.redirect = true;
```

3. Refresh webscript in http://192.168.33.23/alfresco/s/index

4. Call http://192.168.33.23/alfresco/s/test/issue?errorcode=400
You can see the chef-alfresco cloud page 

![cloudpage](https://cloud.githubusercontent.com/assets/6482939/23995479/a8dd6576-0a41-11e7-873d-df7d1e30963c.png)

5. Call http://192.168.33.23/alfresco/s/test/issue?errorcode=401
You can see the error message not handled by haproxy

![errormessage](https://cloud.githubusercontent.com/assets/6482939/23995508/cd20ff56-0a41-11e7-922c-21e882891a46.png)

FIX:
Error codes should be parametrised, so overriding it with empty value it won't ever use that page.

**Comment by marcomancuso** [comment]
https://github.com/Alfresco/chef-alfresco/pull/212/files
