### ISSUE TITLE
metadata.rb on v.0.7.29?

### ISSUE THREAD

**Issue by mtwallach** [Alfresco/chef-alfresco#241]
Why does the metadata.rb specifying 0.7.28?

name             'alfresco'
maintainer       'Alfresco T&A'
maintainer_email 'enzo.rivello@alfresco.com'
license          'Apache 2.0'
description      'Installs Alfresco Community and Enterprise Edition.'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
issues_url       'https://github.com/Alfresco/chef-alfresco/issues'
source_url       'https://github.com/Alfresco/chef-alfresco'
version '0.7.28'

**Comment by marcomancuso** [comment]
Hi @mtwallach, that is in fact an error, it's been fixed in newer releases
