### ISSUE TITLE
berks install failing

### ISSUE THREAD

**Issue by mtwallach** [Alfresco/chef-alfresco#242]
running berks install is failing with following:
The dependency constraints could not be solved in the time allotted.
Unable to find a solution for demands: alfresco (0.7.27), commons (0.5.4), database (5.0.0), file (2.0.0), maven (1.2.0), tomcat (11.17.3)

tried changing database version to 4.0.6 and it also fails

**Comment by marcomancuso** [comment]
This should be fixed in v0.7.31, please let me know if it works there.

**Comment by mtwallach** [comment]
sorry for delay, yes that worked fine. thanks!
