### ISSUE TITLE
Mixup of ImageMagick version logic inside transformations.rb recipe

### ISSUE THREAD

**Issue by amohammedalfresco** [Alfresco/chef-alfresco#257]
There seems to be an issue with the logic of installing ImageMagick version with enable of `use_imagemagick_os_repo` or explicit version `imagemagick_version` via `install_imagemagick` attributes.

If both `use_imagemagick_os_repo` and `install_imagemagick` are set `true`, it will not install supported/expected version i.e.`6.9.5-9`

```
* rpm_package[/tmp/kitchen/cache/ImageMagick-libs-6.9.5-9.x86_64.rpm] action install[2017-09-26T16:17:35+00:00] INFO: Processing rpm_package[/tmp/kitchen/cache/ImageMagick-libs-6.9.5-9.x86_64.rpm] action install (alfresco::transformations line 122)
(skipped due to not_if)
* remote_file[/tmp/kitchen/cache/ImageMagick-6.9.5-9.x86_64.rpm] action create[2017-09-26T16:17:35+00:00] INFO: Processing remote_file[/tmp/kitchen/cache/ImageMagick-6.9.5-9.x86_64.rpm] action create (alfresco::transformations line 128)
(skipped due to not_if)
* rpm_package[/tmp/kitchen/cache/ImageMagick-6.9.5-9.x86_64.rpm] action install[2017-09-26T16:17:35+00:00] INFO: Processing rpm_package[/tmp/kitchen/cache/ImageMagick-6.9.5-9.x86_64.rpm] action install (alfresco::transformations line 134)
(skipped due to not_if)
```

**Comment by marcomancuso** [comment]
we really should not support the `use_imagemagick_os_repo` logic and always use the defined imagemagick version

**Comment by amohammedalfresco** [comment]
After going through debugging of issue, I noted the use of `use_imagemagick_os_repo` was meant for those end user's OS what don't have dependencies issues when an explicit version is set.  For example on Centos X OS, not every archived version of imagemagick installation is successful as it might have many dependencies issues (like libsxxx that is needed by a particular provided version of ImageMagick).

Hence, to avoid community users to experience rpm installation dependencies issues, we are simply installing ImageMagick from community cookbook which should install the latest version from the OS enabled yum repos.

If the end user want to explicitly pin to a particular version then `use_imagemagick_os_repo` must be `false` so the provided version will be evaluated (but there is no guarantee it will be successfully installed as rpm/yumlocal may hit dependencies issues).
