### ISSUE TITLE
Logstash bad attributes

### ISSUE THREAD

**Issue by sergiuv2020** [Alfresco/chef-alfresco#26]
https://github.com/Alfresco/chef-alfresco/blob/master/recipes/logstash-forwarder.rb#L2-L7
Hardcoded auto-generated path, NO NO NO. This will never work on different versions of tomcat or different os's.

**Comment by maoo** [comment]
Agreed. let's change this as soon as we have a consolidated approach to Tomcat installation

**Comment by enzor** [comment]
is this still an issue?
