### ISSUE TITLE
Security Issue(?)

### ISSUE THREAD

**Issue by mtwallach** [Alfresco/chef-alfresco#78]
Someone using chef-alfresco had been working with some Chef Engineers and they pointed out possible security issue(?):
Based on consultation with Chef this week and whilst working on some details to build a wrapper for chef-alfresco we came across a security issue.

The problem in a nutshell is that attributes are being used set information that should be set via data bag’s or variables generated during the chef-client run.
Attributes available to anyone with access to the system which is very bad as far as I can tell ;) .
This presents a difficult problem for my team.

Ideally I would like to be able to wrap the chef-alfresco cookbook with our own; without applying any monkey patches,
since this negates the initial advantages gained by wrapping the code as opposed to modifying our own version and trying to keep them in sync. 
Ideally we should be able to wrap your cookbook without exposing sensitive information to users.

As an example if you type password into the search criteria in the git hub project you will find a number of examples where default password information is passed into and attribute.
According to Chef attributes should only be used for persistent data and not for values that should be secret or dynamic.

Can provide example if needed

**Comment by justindossey** [comment]
This is correct-- passwords shouldn't be in node attributes.

**Comment by enzor** [comment]
Hi Mike,

proper management of secrets through databags will be fully supported early next year, in our 0.9 milestone, when we are going to make our cookbooks fully working with chef-server, with a proper workflow.

**Comment by mtwallach** [comment]
Hello,
What is timeline for Release 0.9. It seems last release was 0.8.x
