### ISSUE TITLE
Solr not working 

### ISSUE THREAD

**Issue by corsarof** [Alfresco/chef-alfresco#9]
After kitchen converge and login correctly into the env solr is not working

**Comment by corsarof** [comment]
Obviously this affects tagging:

org.alfresco.repo.search.impl.lucene.LuceneQueryParserException: 04260100 Request failed 404 /solr4/alfresco/alfresco?wt=json&fl=DBID%2Cscore&rows=1000&df=TEXT&start=0&locale=en_GB&alternativeDic=DEFAULT_DICTIONARY&fq=%7B%21afts%7DAUTHORITY_FILTER_FROM_JSON&fq=%7B%21afts%7DTENANT_FILTER_FROM_JSON

**Comment by maoo** [comment]
fixed on master
